repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      - id: block-env
        name: Block committing .env files
        entry: bash -c 'if git diff --cached --name-only | grep -E "^\.env(\.|$)"; then echo "Refusing to commit .env files"; exit 1; fi'
        language: system
        pass_filenames: false
