# Generated by Django 5.2.4 on 2025-08-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_change_product_price', 'Can change product price')]},
        ),
    ]
